# Usar a imagem oficial do PostgreSQL
FROM postgres:15

# Definir as variáveis de ambiente para o banco de dados
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=nestjs_db

# Expor a porta padrão do PostgreSQL
EXPOSE 5432
